# Generated by Django 5.0.7 on 2024-08-06 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
                ('btn_title', models.CharField(blank=True, max_length=20, null=True)),
                ('open_link_in', models.CharField(choices=[('new_tab', 'New Tab'), ('same_tab', 'Same Tab'), ('modal', 'Modal')], default='new_tab', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('color', models.CharField(default='#000000BF', max_length=15)),
                ('mode', models.CharField(choices=[('draw', 'Draw'), ('view', 'View')], default='view', max_length=5)),
                ('zoom', models.CharField(choices=[('always', 'Always'), ('zoom_range', 'Zoom Range')], default='always', max_length=15)),
                ('zoom_range', models.IntegerField(default=0)),
                ('kml_file', models.FileField(blank=True, null=True, upload_to='drawing/kml_file/')),
            ],
        ),
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marker_type', models.CharField(choices=[('shape', 'Shape'), ('image', 'Image')], default='shape', max_length=10)),
                ('size', models.IntegerField(default=35)),
                ('image', models.FileField(blank=True, null=True, upload_to='marker/')),
                ('color', models.CharField(default='#4D5E6AFF', max_length=15)),
                ('marker_text', models.CharField(blank=True, max_length=255, null=True)),
                ('text_size', models.IntegerField(default=60)),
            ],
        ),
        migrations.CreateModel(
            name='PositionView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoom_lvl', models.DecimalField(decimal_places=2, default=12.0, max_digits=5)),
                ('effect_3d', models.DecimalField(decimal_places=2, default=60.0, max_digits=5)),
                ('lat', models.DecimalField(decimal_places=12, default=0.0, max_digits=15)),
                ('long', models.DecimalField(decimal_places=12, default=0.0, max_digits=15)),
                ('rotation', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='main.category')),
                ('drawing', models.ManyToManyField(blank=True, related_name='categories', to='main.drawing')),
                ('marker', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.marker')),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True, null=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to='map/logo/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('publish', 'Published')], default='draft', max_length=20)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('action_btn', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.actionbutton')),
                ('drawing', models.ManyToManyField(blank=True, related_name='maps', to='main.drawing')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('show_address', models.BooleanField(default=True)),
                ('show_3d_building', models.BooleanField(default=False)),
                ('desc', models.TextField(blank=True, null=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='location/audio/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('publish', 'Published')], default='draft', max_length=20)),
                ('action_btn', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.actionbutton')),
                ('category', models.ManyToManyField(blank=True, related_name='locations', to='main.category')),
                ('drawing', models.ManyToManyField(blank=True, related_name='locations', to='main.drawing')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='main.map')),
                ('marker', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.marker')),
                ('position_view', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.positionview')),
            ],
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('pdf', 'PDF')], default='image', max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='media/')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='main.location')),
            ],
        ),
    ]
