# Generated by Django 5.0.7 on 2024-08-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='map',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='marker',
            name='color',
            field=models.CharField(blank=True, default='#4D5E6AFF', max_length=15),
        ),
        migrations.AlterField(
            model_name='marker',
            name='size',
            field=models.IntegerField(blank=True, default=35),
        ),
        migrations.AlterField(
            model_name='marker',
            name='text_size',
            field=models.IntegerField(blank=True, default=60),
        ),
    ]
